/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolerpinvoicemydata;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author vbat
 */
public class adminMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form adminMainFrame
     */
    public adminMainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldUserName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jButtonNewUser = new javax.swing.JButton();
        jButtonDeleteUser = new javax.swing.JButton();
        jButtonUpdatePassword = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Password:");

        jLabel5.setText("UserName:");

        jLabel2.setText("Please enter credential to continue");

        jLabel6.setText("re-enter password:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPasswordField)
                    .addComponent(jTextFieldUserName))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jButtonNewUser.setText("Add User");
        jButtonNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewUserActionPerformed(evt);
            }
        });

        jButtonDeleteUser.setText("Delete User");
        jButtonDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteUserActionPerformed(evt);
            }
        });

        jButtonUpdatePassword.setText("Update Password");
        jButtonUpdatePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdatePasswordActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jButtonNewUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButtonUpdatePassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDeleteUser)
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(84, 84, 84)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(111, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(138, 138, 138)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(138, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNewUser)
                    .addComponent(jButtonDeleteUser)
                    .addComponent(jButtonUpdatePassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(91, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(144, 144, 144)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(144, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewUserActionPerformed
        // TODO add your handling code here:
        if((jTextFieldUserName.getText().equals("")) || (jPasswordField.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "Username or Password field is empty", this.getTitle(), JOptionPane.WARNING_MESSAGE);
        }else if((passwordValidationCheck() != true) ||(passwordValidationCheckReEnter() != true) ){
            System.out.println("issue");
        }else if(Integer.parseInt(jPasswordField.getText())!= Integer.parseInt(jPasswordField1.getText())){
            JOptionPane.showMessageDialog(null, "Passwords don't match.. please re-enter correctly", this.getTitle(), JOptionPane.WARNING_MESSAGE);
        }else{
            if(databaseRecordCheck() == true){
                JOptionPane.showMessageDialog(null, "UserName already exists. Please enter a new one", this.getTitle(), JOptionPane.WARNING_MESSAGE);
            }else{
                try{
                    Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/InvoiceMyDataAPI","sa","sa");
                    //Statement stmt = con.createStatement();
                    PreparedStatement ps = con.prepareStatement("INSERT INTO SA.EMPLOYEES VALUES (?,?)");
                    ps.setString(1, jTextFieldUserName.getText());
                    ps.setString(2, jPasswordField.getText());
                    int dialogButton = 0;
                    int dialogResult = JOptionPane.showConfirmDialog (null, "add user: "+jTextFieldUserName.getText()+" ?","Warning",dialogButton);
                    if(dialogResult == JOptionPane.YES_OPTION){
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(null, "User created succesfully", this.getTitle(), JOptionPane.WARNING_MESSAGE);
                        jTextFieldUserName.setText("");
                        jPasswordField.setText("");
                        jPasswordField1.setText("");
                    }
                }catch(SQLException e){
                    System.out.println(e);
                }
            }
        }
    }//GEN-LAST:event_jButtonNewUserActionPerformed

    private void jButtonDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteUserActionPerformed
        int passwordField1 = Integer.parseInt(jPasswordField.getText());
        int passwordField2 = Integer.parseInt(jPasswordField1.getText());
        System.out.println(passwordField1 +"\t"+passwordField2);
        
        String UPDATE_QUERY = "DELETE FROM SA.EMPLOYEES WHERE USERNAME = ?";
        if((jTextFieldUserName.getText().equals("")) || (jPasswordField.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "Username or Password field is empty", this.getTitle(), JOptionPane.WARNING_MESSAGE);
        }else if((passwordValidationCheck() != true) ||(passwordValidationCheckReEnter() != true) ){
            System.out.println("okkkk");
        }else if(passwordField1 != passwordField2){
            JOptionPane.showMessageDialog(null, "Passwords don't match.. please re-enter correctly", this.getTitle(), JOptionPane.WARNING_MESSAGE);
        }else{
            if(databaseRecordCheck() != true){
                JOptionPane.showMessageDialog(null, "Cannot find User Name", this.getTitle(), JOptionPane.WARNING_MESSAGE);
            }else{
                try{
                    Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/InvoiceMyDataAPI","sa","sa");
                            PreparedStatement ps = con.prepareStatement(UPDATE_QUERY);
                            ps.setString(1, jTextFieldUserName.getText());
                            int dialogButton = 0;
                            int dialogResult = JOptionPane.showConfirmDialog (null, "Are you sure you want to delete user: "+jTextFieldUserName.getText()+" ?","Warning",dialogButton);
                            if(dialogResult == JOptionPane.YES_OPTION){
                                ps.executeUpdate();
                                JOptionPane.showMessageDialog(null, "user "+jTextFieldUserName+" deleted succesfully", this.getTitle(), JOptionPane.WARNING_MESSAGE);
                                jTextFieldUserName.setText("");
                                jPasswordField.setText("");
                                jPasswordField1.setText("");
                        }
                }catch(SQLException e){
                    System.out.println(e);
                }
            }
        }
    }//GEN-LAST:event_jButtonDeleteUserActionPerformed

    private void jButtonUpdatePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdatePasswordActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        int passwordField1 = Integer.parseInt(jPasswordField.getText());
        int passwordField2 = Integer.parseInt(jPasswordField1.getText());
        System.out.println(passwordField1 +"\t"+passwordField2);
        
        String UPDATE_QUERY = "UPDATE SA.EMPLOYEES SET PASSWORD = ? WHERE USERNAME = ?";
        if((jTextFieldUserName.getText().equals("")) || (jPasswordField.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "Username or Password field is empty", this.getTitle(), JOptionPane.WARNING_MESSAGE);
        }else if((passwordValidationCheck() != true) ||(passwordValidationCheckReEnter() != true) ){
            System.out.println("okkkk");
        }else if(passwordField1 != passwordField2){
            JOptionPane.showMessageDialog(null, "Passwords don't match.. please re-enter correctly", this.getTitle(), JOptionPane.WARNING_MESSAGE);
        }else{
            if(databaseRecordCheck() != true){
                JOptionPane.showMessageDialog(null, "Cannot find User Name", this.getTitle(), JOptionPane.WARNING_MESSAGE);
            }else{
                try{
                    Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/InvoiceMyDataAPI","sa","sa");
                        PreparedStatement ps = con.prepareStatement(UPDATE_QUERY);
                        ps.setInt(1,Integer.parseInt(jPasswordField.getText()));
                        ps.setString(2, jTextFieldUserName.getText());
                        int dialogButton = 0;
                        int dialogResult = JOptionPane.showConfirmDialog (null, "Are you sure you want to change password for user: "+jTextFieldUserName.getText()+" ?","Warning",dialogButton);
                        if(dialogResult == JOptionPane.YES_OPTION){
                            ps.executeUpdate();
                            JOptionPane.showMessageDialog(null, "Password changed succesfully", this.getTitle(), JOptionPane.WARNING_MESSAGE);
                            jTextFieldUserName.setText("");
                            jPasswordField.setText("");
                            jPasswordField1.setText("");
                        }
                }catch(SQLException e){
                    System.out.println(e);
                }
            }
        }
    }//GEN-LAST:event_jButtonUpdatePasswordActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String UPDATE_QUERY = "SELECT * FROM SA.EMPLOYEES";
        try{
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/InvoiceMyDataAPI","sa","sa");
            PreparedStatement ps = con.prepareStatement(UPDATE_QUERY);
            ps.setInt(1,Integer.parseInt(jPasswordField.getText()));
            ps.setString(2, jTextFieldUserName.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Password changed succesfully", this.getTitle(), JOptionPane.WARNING_MESSAGE);
            jTextFieldUserName.setText("");
        
        }catch(SQLException e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminMainFrame().setVisible(true);
            }
        });
    }
    
        private Boolean databaseRecordCheck(){
        Boolean isEmpty = false;
        String userName = jTextFieldUserName.getText();
        String SELECT_QUERY = "SELECT * FROM SA.EMPLOYEES WHERE USERNAME = '"+userName+"'";//"SELECT * FROM SA.EMPLOYEES WHERE USERNAME = "+userName;
        
        try{
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/InvoiceMyDataAPI","sa","sa");
            Statement stmt = con.createStatement();
            ResultSet result = stmt.executeQuery(SELECT_QUERY);
            System.out.println(result);
            System.out.println(isEmpty);
            if(result.next() == false){
                isEmpty = false;
            }else{
                isEmpty = true;
                do{ 
                    String uname = result.getString("USERNAME");
                    String password = result.getString("PASSWORD");
                    System.out.println(isEmpty);
                    System.out.println("UserName: "+userName+ "\t"+ "PassWord: "+password);
                }while(result.next());
            }
            
        }catch(SQLException e){
            System.out.println(e);
        }
        return isEmpty;
        
    }
    
    private Boolean passwordValidationCheck(){
        Boolean isNumber = false;
        while(true){
            try{
                Integer.parseInt(jPasswordField.getText());
                //JOptionPane.showMessageDialog(null, "Password Accepted", this.getTitle(), JOptionPane.WARNING_MESSAGE);
                isNumber = true;
                break;
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Only numbers are allowed", this.getTitle(), JOptionPane.WARNING_MESSAGE);
                isNumber = false;
                break;
            }
        }
        
        
        return isNumber;
    }

    private Boolean passwordValidationCheckReEnter(){
        Boolean isNumber = false;
        while(true){
            try{
                Integer.parseInt(jPasswordField1.getText());
                //JOptionPane.showMessageDialog(null, "Password Accepted", this.getTitle(), JOptionPane.WARNING_MESSAGE);
                isNumber = true;
                break;
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Only numbers are allowed", this.getTitle(), JOptionPane.WARNING_MESSAGE);
                isNumber = false;
                break;
            }
        }
        
        
        return isNumber;
    }            

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeleteUser;
    private javax.swing.JButton jButtonNewUser;
    private javax.swing.JButton jButtonUpdatePassword;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}
